"""
Daily market bias report generator.
Produces a markdown summary for a given symbol (default: SPY/QQQ).
"""
from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from providers.base import BaseProvider


async def generate_daily_bias_report(symbol: str, provider: "BaseProvider") -> str:
    """
    Generate a markdown daily bias report for *symbol*.
    Uses recent price history + options chain data to assess directional bias.
    """
    try:
        bars = await provider.get_history(symbol, timeframe="1Day", limit=20)
        quote = await provider.get_quote(symbol)
    except Exception as e:
        return f"# {symbol} Daily Bias Report\n\n⚠️ Could not fetch data: {e}"

    if not bars:
        return f"# {symbol} Daily Bias Report\n\n⚠️ No historical data available."

    closes = [b["close"] for b in bars]
    spot = float(quote.get("last_price") or closes[-1])

    # Simple indicators
    sma5 = sum(closes[-5:]) / 5
    sma20 = sum(closes[-20:]) / len(closes)
    pct_change = ((closes[-1] - closes[-2]) / closes[-2] * 100) if len(closes) >= 2 else 0
    above_sma5 = spot > sma5
    above_sma20 = spot > sma20

    trend = "🟢 Bullish" if above_sma5 and above_sma20 else (
        "🔴 Bearish" if not above_sma5 and not above_sma20 else "🟡 Mixed"
    )

    # Try to get GEX data for key levels
    gex_section = ""
    try:
        from services.gex import compute_gex
        from services.oi import compute_oi
        chain = await provider.get_options_chain(symbol)
        if chain:
            gex_data = compute_gex(chain, spot)
            # Find max GEX strike (resistance/support)
            if gex_data:
                max_gex = max(gex_data, key=lambda x: abs(x["gex"]))
                gex_section = f"\n### ⚡ Key GEX Level\n- **${max_gex['strike']:.0f}** — {max_gex['gex']:,.0f} GEX (major gamma pin)\n"
    except Exception:
        pass

    report = f"""# {symbol} Daily Bias Report

**Date:** {bars[-1].get('timestamp', 'N/A')[:10] if bars else 'N/A'}
**Spot:** ${spot:.2f}
**Daily Change:** {pct_change:+.2f}%

## Trend: {trend}

| Indicator | Value | Signal |
|-----------|-------|--------|
| SMA 5 | ${sma5:.2f} | {'Above ✅' if above_sma5 else 'Below ❌'} |
| SMA 20 | ${sma20:.2f} | {'Above ✅' if above_sma20 else 'Below ❌'} |
{gex_section}
## Bias Summary
{"Price is trading above both the 5-day and 20-day moving averages, suggesting near-term bullish momentum. Look for long setups on pullbacks." if above_sma5 and above_sma20 else
 "Price is trading below both the 5-day and 20-day moving averages, suggesting near-term bearish pressure. Look for short setups on bounces." if not above_sma5 and not above_sma20 else
 "Price is showing mixed signals between short and medium-term moving averages. Wait for a clearer directional break before committing."}

*Generated by CrystalBall — [crystalball.dev](https://crystalball.dev)*
"""
    return report
